AWSTemplateFormatVersion: 2010-09-09
Description: Cross Account Basic Pipeline

Parameters:
  ProjectName:
    Type: String
    Default: cross-account
    Description: Name for the Project (NB must be lowercase)
  DevAccountNo:
    Type: String
    Description: The Account Number of the dev account
  ProdAccountNo:
    Type: String
    Description: The Account Number of the prod account
  CodeBuildEnvironment:
    Type: String
    Default: "aws/codebuild/standard:5.0"
  CodeStarConnectionArn:
    Type: String
    Description: The codestar connection used to connect to github
  BranchName:
    Type: String
    Description: The name of the branch to trigger the pipeline from
    Default: "pipeline/basic"
  SourceRepository:
    Type: String
    Description: The Fully qualified repository name
    Default: scottjbaldwin/AWSCrossAccountDeployment
    
Resources:
  ArtefactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-artefactbucket
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: 
                Fn::ImportValue: 
                  !Sub '${ProjectName}:ArtefactKMSKey'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
        - Id: Purge after 7 days of creation
          ExpirationInDays: 7
          Status: Enabled
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  ArtefactBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref ArtefactBucket
      PolicyDocument: 
        Statement: 
          - Sid: ServicePermit
            Effect: Allow
            Principal:
              Service: 
                - codebuild.amazonaws.com
                - codepipeline.amazonaws.com
            Action: 's3:*'
            Resource: !Sub 'arn:aws:s3:::${ProjectName}-artefactbucket'
          - Sid: AllowTargetAccountsAccessS3
            Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${DevAccountNo}:root'
                - !Sub 'arn:aws:iam::${ProdAccountNo}:root'
            Action: 's3:*'
            Resource: 
              - !Sub 'arn:aws:s3:::${ProjectName}-artefactbucket/*'
              - !Sub 'arn:aws:s3:::${ProjectName}-artefactbucket'

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}_build'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}_build:*'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
              - Effect: Allow
                Resource: !Sub "arn:aws:s3:::${ProjectName}-artefactbucket/*"
                Action: 
                  - s3:*
              - Effect: Allow
                Resource: !Sub "arn:aws:s3:::${ProjectName}-artefactbucket"
                Action: 
                  - s3:*
              - Effect: Allow
                Action:
                  - 'codebuild:*'
                  - 'codepipeline:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:DescribeKey*
                  - kms:GenerateDataKey
                Resource: 
                  Fn::ImportValue: 
                    !Sub '${ProjectName}:ArtefactKMSKey'
              - Effect: Allow
                Action:
                  - 'kms:ListKeys'
                  - 'kms:ListAliases'
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # CodeBuild
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}_build'
      Description: Builds the backend services and creates a cloudformation template to deploy them
      Artifacts:
        Type: CODEPIPELINE
      Environment: 
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Sub '${CodeBuildEnvironment}'
        EnvironmentVariables:
          - Name: BUILD_OUTPUT_BUCKET
            Value: !Sub ${ProjectName}-artefactbucket
          - Name: AWS_REGION
            Value: !Sub ${AWS::Region}
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source: 
        Type: CODEPIPELINE
        BuildSpec: BasicPipeline/buildspec.yml
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 
            - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: 
                - codepipeline.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSCodeCommitFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'iam:PassRole'
                Effect: Allow
                Resource: '*'
              - Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:DescribeKey*
                  - kms:GenerateDataKey
                Effect: Allow
                Resource:
                  Fn::ImportValue: 
                    !Sub '${ProjectName}:ArtefactKMSKey'
              - Action:
                  - 'kms:ListKeys'
                  - 'kms:ListAliases'
                Effect: Allow
                Resource: '*'
              - Action:
                  - 'codestar-connections:UseConnection'
                Effect: Allow
                Resource:
                  - !Ref CodeStarConnectionArn
              - Action:
                  - 'codebuild:StartBuild'
                  - 'codebuild:BatchGetBuilds'
                Effect: Allow
                Resource:
                  - !GetAtt CodeBuildProject.Arn

                  
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  Pipeline:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        Tags:
          - Key: Project
            Value: !Ref ProjectName
        ArtifactStore: 
            Location: !Sub ${ProjectName}-artefactbucket
            Type: S3
            EncryptionKey:
              Id: 
                Fn::ImportValue:
                  !Sub '${ProjectName}:ArtefactKMSKey'
              Type: KMS
        Name: !Sub ${ProjectName}_pipeline
        RoleArn: !GetAtt PipelineExecutionRole.Arn
        Stages:
            - Name: Source
              Actions:
                - Name: GitHubRepo
                  ActionTypeId:
                    Category: Source
                    Owner: AWS
                    Provider: CodeStarSourceConnection
                    Version: '1'
                  Configuration:
                    ConnectionArn: !Ref CodeStarConnectionArn
                    FullRepositoryId: !Ref SourceRepository
                    DetectChanges: true
                    BranchName: !Ref BranchName
                  OutputArtifacts:
                    - Name: SourceArtefact
                  RunOrder: 1
            - Name: Build
              Actions:
                - Name: CodeBuild
                  ActionTypeId:
                    Category: Build
                    Owner: AWS
                    Provider: CodeBuild
                    Version: '1'
                  Configuration:
                    ProjectName: !Ref CodeBuildProject
                  InputArtifacts:
                    - Name: SourceArtefact
                  OutputArtifacts:
                    - Name: OutputArtefact
                  RunOrder: 1